Update ux-ui-designer-researcher.md
compilerla/compiler.la pull request #185
Opened 2024-04-02 19:17 UTC by mrose914

Updates Design Contractor position based on feedback from @srhhnry

2024-04-02 19:38 UTC, thekaveman requested changes

2024-04-02 19:38 UTC, thekaveman commented on _jobs/ux-ui-designer-researcher.md
> +**Overview:** The Senior Consultant UX/UI Designer and Researcher leads user research and design for two major portfolio projects, the CA Mobility Marketplace (camobilitymarketplace.org) and the Cal-
```suggestion
**Overview:** The Senior Consultant UX/UI Designer and Researcher leads user research and design for two major portfolio projects, the CA Mobility Marketplace ([camobilitymarketplace.org](https://camobilitymarketplace.org)) and the Cal-ITP homepage ([calitp.org](https://calitp.org)) in collaboration with the senior product manager. Responsibilities will include designing and executing user research efforts, user testing execution and synthesis, delivering design mockups for web applications, and collaborating with the engineering team on best practices in building inclusive and accessible solutions.
```

Let's add the links to these sites for easier navigation

2024-04-02 19:38 UTC, thekaveman commented on _jobs/ux-ui-designer-researcher.md
> +Send resume, brief intro email and preferences for working (hours, time zone, etc) to [careers@compiler.la](mailto:careers@compiler.la) by April 12, 2024.
Let's check with @shelby-e, I think we'll want to use our new ClickUp process for this instead of an email inbox.

2024-04-02 22:45 UTC, AnthonyRollins commented
@mrose914 @thekaveman Here's the application link: https://forms.clickup.com/8631512/f/87d6r-14154/EYTB48KL0KYX71LH1Q?Job%20Role=UX/UI%20Designer

Please use the full link as the last part,`?Job%20Role=UX/UI%20Designer` auto-fills a field in ClickUp

2024-04-02 23:09 UTC, thekaveman requested changes

2024-04-02 23:09 UTC, thekaveman commented on _jobs/ux-ui-designer-researcher.md
> +Please apply using [this form](https://forms.clickup.com/8631512/f/87d6r-14154/EYTB48KL0KYX71LH1Q?Job%20Role=UX%2FUI%20Designer). We look forward to hearing from you!
Ah sorry @mrose914 I should have been more clear:

The link should be added to the top "front matter" (everything between `---`) like:

```
---
type: Contract
apply_link: https://forms.clickup.com/8631512/f/87d6r-14154/EYTB48KL0KYX71LH1Q?Job%20Role=UX%2FUI%20Designer
---
```

This makes the "Apply" button show up on the post page and link to the form (and only during the job open window).

Check out the SE post for an example: https://github.com/compilerla/compiler.la/blob/main/_jobs/software-engineer.md

2024-04-03 01:34 UTC, thekaveman approved these changes
Looks great! I'll merge @mrose914

2024-04-03 01:35 UTC, merged