Feat: create redirects for logo files
compilerla/compiler.la pull request #235
Opened 2024-07-26 18:09 UTC by angela-tran

`/logo-dark` goes to the logo with dark text
`/logo-light` goes to the logo with light text

2024-07-26 18:12 UTC, angela-tran commented on src/assets/compiler_logo_stacked_WhiteTeal.png
I grabbed both logo files from Google Drive (`Compiler Branding Identity` > `Brand Kit` > `Logo` > `Logo Stacked` > `PNG`)

The files `Compiler Logo_Stacked_WhiteTeal.png` and `Compiler Logo_Stacked_WhiteGreen.png` for some reason don't actually use the teal or green color.

2024-07-26 18:19 UTC, angela-tran commented
Preview:

https://deploy-preview-235--compilerla.netlify.app/logo-dark
https://deploy-preview-235--compilerla.netlify.app/logo-light

2024-07-26 18:23 UTC, angela-tran commented on src/assets/compiler_logo_stacked_WhiteTeal.png
Looks like I edited the SVG myself to get teal into the white SVG currently used on the site


![image](https://github.com/user-attachments/assets/ab64c212-fa6c-4a22-8d90-bc5c9dd6931c)

[source](https://github.com/compilerla/compiler.la/commits/02f091035624fbe51bf83ec12b48c11ec2cd9b02/assets/compiler_logo_stacked.svg?browsing_rename_history=true&new_path=src/assets/compiler_logo_stacked.svg&original_branch=feat/links-to-logos)

2024-07-26 19:47 UTC, thekaveman requested changes
@AnthonyRollins and I have been looking at this PR and talking about it a bit here.

@angela-tran what do you think about, instead of having each of these logos with their own redirect, we create a single page called `/brand` with a table of each logo option? We can eventually use this as an external "brand kit" type page, and for now it will serve the use case of #168.

This is similar to the idea in #49 too, but more for an external audience whereas the style guide is more an internal/website team audience.

2024-07-26 20:46 UTC, angela-tran commented on src/assets/compiler_logo_stacked_WhiteTeal.png
Open question on if this logo is ok for the light version

2026-08-07 16:39 UTC, thekaveman commented
@AnthonyRollins and I were chatting about this idea again yesterday. Closing this PR, Anthony is going to write up a new issue to map out what we want to have on the `/brand` page.

Also, this was from the before-times Jekyll days :grin:

2026-08-07 16:39 UTC, closed without merging