Colors only
compilerla/compiler.la pull request #95
Opened 2023-07-27 19:39 UTC by machikoyasuda

closes #37  but only for colors

- This PR _only_ touches on colors, not fonts or any button styling unrelated to colors.
- After this PR, all colors should be declared with a variable. New variables can be added as necessary.
- Variable color names largely come from Figma
- Adds some Bootstrap overrides for `body` colors
- Doesn't add any Bootstrap overrides for `primary` or `secondary` etc. colors yet. It's too early I think.
- Removed colors not used
- Teal is now called Cyan

Things that actually changed from this PR, aside from variables:
- Background color changed from `#262626` to `#1c1c1c`
- Text on the homepage changed from `#01B4CB` to `#51B1C7`

2023-07-27 20:49 UTC, machikoyasuda commented on styles/base.css
> +    --brand-primary-white: #FFFFFF;
From https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=1358-19464&mode=dev

2023-07-27 20:51 UTC, machikoyasuda commented on styles/base.css
> +    --text-black: #1C1C1C;
Colors from https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/Current-compiler.la?type=design&node-id=1358-19464&mode=dev

2023-07-27 20:51 UTC, machikoyasuda commented on styles/base.css
> +    font-family: 'Roboto', Arial, sans-serif;
This will be removed with #94

2023-07-28 06:20 UTC, machikoyasuda commented
I decided it was easier to review this all in 1 PR, rather than scattered across 4-5 PRs :)

2023-07-28 15:33 UTC, thekaveman requested changes
> I decided it was easier to review this all in 1 PR, rather than scattered across 4-5 PRs :)

I disagree. This PR is massive and focuses on way more than the Home page / colors. 

#82 is our priority for right now. I'm not sure why #49 was folded in here as well, that one was not prioritized for dev work on the Project board. 

Please focus PRs on one issue at a time.

2023-08-21 20:09 UTC, closed without merging